import { Dimensions, StyleSheet } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const PADDING = 10;
const AVAILABLE_WIDTH = SCREEN_WIDTH - (PADDING * 2);

// Horizontal Table Layout - Responsive scaling
// We want the table + seats to fit. Seats are SEAT_SIZE and touch the table.
// Total width needed is TABLE_WIDTH + SEAT_SIZE * 2
export const TABLE_WIDTH = Math.min(AVAILABLE_WIDTH * 0.75, 400);
export const TABLE_HEIGHT = TABLE_WIDTH * 0.52;
export const SEAT_SIZE = Math.min(AVAILABLE_WIDTH * 0.12, 48);

export const styles = StyleSheet.create({
  tableContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 45, // Space for seats at top/bottom
    paddingHorizontal: PADDING,
    minHeight: TABLE_HEIGHT + 160, 
  },
  table: {
    width: TABLE_WIDTH,
    height: TABLE_HEIGHT,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tableFelt: {
    width: '100%',
    height: '100%',
    backgroundColor: '#27ae60',
    borderRadius: TABLE_HEIGHT / 2, 
    borderWidth: Math.max(10, TABLE_WIDTH * 0.04),
    borderColor: '#3e2723', 
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  tableText: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: Math.max(10, TABLE_WIDTH * 0.04),
    textAlign: 'center',
    width: '60%',
  },
  seat: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -SEAT_SIZE / 2,
    marginLeft: -SEAT_SIZE / 2,
    width: SEAT_SIZE,
    height: SEAT_SIZE,
    borderRadius: SEAT_SIZE / 2,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#ddd',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  seatOccupied: {
    backgroundColor: '#e3f2fd',
    borderColor: '#2196f3',
  },
  seatHero: {
    backgroundColor: '#fff3e0',
    borderColor: '#ff9800',
  },
  seatPlayerName: {
    fontSize: Math.max(7, SEAT_SIZE * 0.16),
    fontWeight: '600',
    color: '#333',
    textAlign: 'center',
    zIndex: 1,
  },
  seatPosition: {
    fontSize: Math.max(6, SEAT_SIZE * 0.14),
    fontWeight: '700',
    color: '#666',
    zIndex: 1,
    marginBottom: 1,
  },
  seatStack: {
    fontSize: Math.max(7, SEAT_SIZE * 0.16),
    fontWeight: '700',
    color: '#333',
    zIndex: 1,
    marginTop: 1,
  },
  seatContent: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  seatTextLight: {
    color: '#fff',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  seatOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: SEAT_SIZE / 2,
  },
  seatNumber: {
    fontSize: Math.max(6, SEAT_SIZE * 0.14),
    color: '#999',
  },
  buttonIndicator: {
    position: 'absolute',
    top: -SEAT_SIZE * 0.12,
    right: -SEAT_SIZE * 0.12,
    width: SEAT_SIZE * 0.35,
    height: SEAT_SIZE * 0.35,
    borderRadius: (SEAT_SIZE * 0.35) / 2,
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#333',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    fontSize: Math.max(7, SEAT_SIZE * 0.15),
    fontWeight: '700',
    color: '#333',
  },
  heroIndicator: {
    position: 'absolute',
    top: SEAT_SIZE * 0.05,
    left: SEAT_SIZE * 0.05,
    width: SEAT_SIZE * 0.3,
    height: SEAT_SIZE * 0.3,
    borderRadius: (SEAT_SIZE * 0.3) / 2,
    backgroundColor: '#ff9800',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  heroText: {
    fontSize: Math.max(8, SEAT_SIZE * 0.18),
    color: '#fff',
  },
  dealer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -TABLE_HEIGHT * 0.12,
    marginLeft: -TABLE_HEIGHT * 0.12,
    width: TABLE_HEIGHT * 0.24,
    height: TABLE_HEIGHT * 0.24,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  dealerText: {
    fontSize: Math.max(7, TABLE_HEIGHT * 0.06),
    color: '#666',
    fontWeight: '600',
    marginTop: -2,
  },
  cardContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -TABLE_HEIGHT * 0.08,
    marginLeft: -TABLE_WIDTH * 0.06, 
    width: TABLE_WIDTH * 0.12,
    height: TABLE_HEIGHT * 0.15,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 0,
  },
  card: {
    width: TABLE_WIDTH * 0.05,
    height: TABLE_HEIGHT * 0.12,
    backgroundColor: '#d32f2f',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: '#fff',
    backfaceVisibility: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardSelected: {
    backgroundColor: '#fff',
  },
  cardText: {
    fontSize: Math.max(7, TABLE_WIDTH * 0.03),
    fontWeight: 'bold',
  },
  cardSuit: {
    fontSize: Math.max(6, TABLE_WIDTH * 0.025),
  },
  cardSecond: {
    marginLeft: 1,
  },
  communityCardsContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -TABLE_HEIGHT * 0.1,
    marginLeft: -TABLE_WIDTH * 0.2, 
    width: TABLE_WIDTH * 0.4,
    height: TABLE_HEIGHT * 0.2,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    gap: 3,
  },
  communityCard: {
    width: TABLE_WIDTH * 0.07,
    height: TABLE_HEIGHT * 0.16,
    backgroundColor: '#d32f2f',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  communityCardSelected: {
    backgroundColor: '#fff',
  },
  communityCardText: {
    fontSize: Math.max(8, TABLE_WIDTH * 0.04),
    fontWeight: 'bold',
  },
  communityCardSuit: {
    fontSize: Math.max(7, TABLE_WIDTH * 0.03),
  },
  potContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -TABLE_HEIGHT * 0.22, // Position above community cards
    marginLeft: -TABLE_WIDTH * 0.15,
    width: TABLE_WIDTH * 0.3,
    height: TABLE_HEIGHT * 0.12,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  potBadge: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: '#ffd700',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  potLabel: {
    color: '#ffd700',
    fontSize: Math.max(8, TABLE_WIDTH * 0.03),
    fontWeight: '700',
  },
  potText: {
    color: '#fff',
    fontSize: Math.max(9, TABLE_WIDTH * 0.035),
    fontWeight: '700',
  },
  blindContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -TABLE_HEIGHT * 0.08,
    marginLeft: -TABLE_WIDTH * 0.08,
    width: TABLE_WIDTH * 0.16,
    height: TABLE_HEIGHT * 0.16,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10, // Ensure bets are above cards
  },
  blindBadge: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1,
  },
  blindText: {
    color: '#fff',
    fontSize: Math.max(7, TABLE_WIDTH * 0.03),
    fontWeight: '700',
  },
  blindLabel: {
    fontSize: Math.max(6, TABLE_WIDTH * 0.025),
    fontWeight: '700',
    color: '#ffd700', 
    marginRight: 1,
  },
});
